import "./globals.css";
import "@fontsource-variable/sen";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className={"font-['Sen Variable', sans-serif,] flex  h-screen "}>{children}</body>
    </html>
  );
}
